### ISSUE TITLE
ShowErrorDialog adds parameter in TP1902.2

### ISSUE THREAD

**Issue by sombrerosheep** [sombrerosheep/TaskSequenceModule#1]
In TP 2902.2 ShowErrorDialog added an 8th parameter to the com object call.

I don't have a readily available environment so getting around to this may not be super quick. Being that this is in TP there's always a chance this doesn't make it to production :wink:

I'd rather have some context to what the parameter is used for. If anyone is interested, inspecting the dll for the exported functions may give us a parameter name. That might be easier than passing a value to that parameter slot and seeing what happens 🤷‍♂️ 

Reported via [twitter](https://twitter.com/gwblok/status/1105213253712576514) by @AdamGrossTX

**Comment by AdamGrossTX** [comment]
Noah, Here's the list of methods from TSProgressUI. The only change in 1901 & 1902 TP is for ShowErrorDialog. The new argument is pszTaskSequenceStepName. I will see about updating the module soon and putting in a PR for it. The main issue will be needing to determine which version of TSProgressUI the client is using then run the appropriate command line.

`CloseProgressDialog()

ShowActionProgress(
    pszOrgName As String, 
    pszTaskSequenceName As String, 
    pszCustomTitle As String, 
    pszCurrentAction As String, 
    uStep As Unsigned Long, 
    uMaxStep As Unsigned Long, 
    pszActionExecInfo As String, 
    uActionExecStep As Unsigned Long, 
    uActionExecMaxStep As Unsigned Long
)

ShowMessage(
    pszText As String, 
    pszCaption As String, 
    uType As Unsigned Long
)

ShowRebootDialog(
    pszOrgName As String, 
    pszTaskSequenceName As String, 
    pszCustomTitle As String, 
    pszRebootMessage As String, 
    uTimeoutInSeconds As Unsigned Long
)

ShowSwapMediaDialog(
    pszTaskSequenceName As String, 
    uMediaNumber As Unsigned Long
)

ShowTSProgress(
    pszOrgName As String, 
    pszTaskSequenceName As String, 
    pszCustomTitle As String, 
    pszCurrentAction As String, 
    uStep As Unsigned Long, 
    uMaxStep As Unsigned Long
)

ShowErrorDialog(
    pszOrgName As String, 
    pszTaskSequenceName As String, 
    pszCustomTitle As String, 
    pszErrorMessage As String, 
    uErrorCode As Unsigned Long, 
    uTimeoutInSeconds As Unsigned Long, 
    bWillReboot As Long, 
    pszTaskSequenceStepName As String
)`
